"""fix statatus  attr from Order table 

Revision ID: 53e3238f3764
Revises: a21ea4bb7638
Create Date: 2024-04-29 20:04:03.625054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e3238f3764'
down_revision: Union[str, None] = 'a21ea4bb7638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
