"""fix statatus  attr from Order table 

Revision ID: 8efd8d5e9aa5
Revises: 53e3238f3764
Create Date: 2024-04-29 20:05:16.502112

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efd8d5e9aa5'
down_revision: Union[str, None] = '53e3238f3764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('orders', 'status',
                    existing_type=postgresql.ENUM('PENDING', 'IN_SHIPPING_CENTER', 'IN_DELIVERY', 'COMPLETED', name='order_status_enum'),
                    server_default='PENDING')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
