"""add quantity attr from Order table 

Revision ID: a21ea4bb7638
Revises: 5b4e169511e4
Create Date: 2024-04-29 19:11:18.084004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21ea4bb7638'
down_revision: Union[str, None] = '5b4e169511e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
